### ISSUE TITLE
Demo doesn't work.

### ISSUE THREAD

**Issue by designforhuman** [EmaSuriano/gatsby-starter-event-calendar#2]
Do you have any plan to fix this?

**Comment by EmaSuriano** [comment]
Hello @designforhuman I'm so sorry that the demo was not working, by accident I was doing a clean up of my Google Drive and I totally forgot about the spreadsheet with the result that's why the calendar was not being rendered 😓 

Anyways, I just create a new spreadsheet and linked it with the starter. Now it should work again! 😄
